# Generated by Django 5.1.2 on 2024-11-03 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='has_weight',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
