# Generated by Django 5.1.2 on 2024-11-14 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_has_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='has_weight',
        ),
    ]
